In [24]:
import pandas as pd

In [25]:
# read the raw data into a dataframe
raw_df = pd.read_csv("raw_data.csv")
raw_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [26]:
# check df shape so that it matches the raw_data.csv: 1500 rows (without the headers) + 8 columns
raw_df.shape

(1500, 8)

In [27]:
# check data types of columns to see if there's anything weird
raw_df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [28]:
# check for missing values
raw_df.isna().sum()

InvoiceNo       0
StockCode       0
Description     1
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID     58
Country         0
dtype: int64

In [29]:
# check for duplicates
raw_df[raw_df.duplicated()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,2010-12-01 11:45:00,1.25,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 11:45:00,2.10,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,2010-12-01 11:45:00,2.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,2010-12-01 11:45:00,4.95,17908.0,United Kingdom
555,536412,22327,ROUND SNACK BOXES SET OF 4 SKULLS,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
587,536412,22273,FELTCRAFT DOLL MOLLY,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
589,536412,22749,FELTCRAFT PRINCESS CHARLOTTE DOLL,1,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
600,536412,22569,FELTCRAFT CUSHION BUTTERFLY,2,2010-12-01 11:49:00,3.75,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,2010-12-01 11:49:00,1.65,17920.0,United Kingdom
605,536412,22902,TOTE BAG I LOVE LONDON,7,2010-12-01 11:49:00,2.10,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
617,536412,22900,SET 2 TEA TOWELS I LOVE LONDON,2,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,2010-12-01 11:49:00,4.95,17920.0,United Kingdom
620,536412,85184C,S/4 VALENTINE DECOUPAGE HEART BOX,1,2010-12-01 11:49:00,2.95,17920.0,United Kingdom
758,536446,21651,HANGING GLASS ETCHED TEALIGHT,6,2010-12-01 12:15:00,1.65,15983.0,United Kingdom
831,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968.0,United Kingdom
835,536464,22945,CHRISTMAS METAL TAGS ASSORTED,6,2010-12-01 12:23:00,0.85,17968.0,United Kingdom
852,536464,21992,VINTAGE PAISLEY STATIONERY SET,1,2010-12-01 12:23:00,2.95,17968.0,United Kingdom
859,536464,22866,HAND WARMER SCOTTY DOG DESIGN,1,2010-12-01 12:23:00,2.10,17968.0,United Kingdom
891,536488,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,1,2010-12-01 12:31:00,2.55,17897.0,United Kingdom
1061,536522,21121,SET/10 RED POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1067,536522,21122,SET/10 PINK POLKADOT PARTY CANDLES,1,2010-12-01 12:49:00,1.25,15012.0,United Kingdom
1140,536528,22865,HAND WARMER OWL DESIGN,1,2010-12-01 13:17:00,2.10,15525.0,United Kingdom
1153,536528,85114B,IVORY ENCHANTED FOREST PLACEMAT,1,2010-12-01 13:17:00,1.65,15525.0,United Kingdom
1159,536528,22584,PACK OF 6 PANNETONE GIFT BOXES,2,2010-12-01 13:17:00,2.55,15525.0,United Kingdom
1165,536528,22911,PAPER CHAIN KIT LONDON,1,2010-12-01 13:17:00,2.95,15525.0,United Kingdom
1166,536528,22743,MAKE YOUR OWN FLOWERPOWER CARD KIT,1,2010-12-01 13:17:00,2.95,15525.0,United Kingdom
1167,536528,22744,MAKE YOUR OWN MONSOON CARD KIT,2,2010-12-01 13:17:00,2.95,15525.0,United Kingdom
1169,536528,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,1,2010-12-01 13:17:00,1.95,15525.0,United Kingdom
1172,536528,84985A,SET OF 72 GREEN PAPER DOILIES,1,2010-12-01 13:17:00,1.45,15525.0,United Kingdom
1179,536528,22839,3 TIER CAKE TIN GREEN AND CREAM,1,2010-12-01 13:17:00,14.95,15525.0,United Kingdom
1205,536530,22097,SWALLOW SQUARE TISSUE BOX,1,2010-12-01 13:21:00,1.25,17905.0,United Kingdom
1222,536531,21498,RED RETROSPOT WRAP,25,2010-12-01 13:23:00,0.42,15485.0,United Kingdom

In [30]:
# count how many duplicate rows there are:
raw_df.duplicated().sum()

np.int64(36)

In [32]:
# NOTICE (to be done in 'transformation'): 
# 1) a lot of generic 'object' types. MUST CHANGE THEM
# 2) customerID is float. CHANGE TO INT
# 3) InvoiceDate is object. CHANGE TO datetime64[ns]
# 4) 1 missing description and 58 missing customerID's 
# 5) There are 36 duplicate rows (they exist at least two times). drop them in transform (use raw_df.drop_duplicates())

In [ ]:
CREATE FILE WITH THE ABOVE INFO